
-- --------------------------------------------------------

--
-- Structure de la table `evenements`
--

CREATE TABLE `evenements` (
  `code_evenement` varchar(8) NOT NULL,
  `nom_evenement` varchar(100) DEFAULT NULL,
  `description_evenement` varchar(1000) DEFAULT NULL,
  `image_evenement` varchar(255) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Contenu de la table `evenements`
--

INSERT INTO `evenements` (`code_evenement`, `nom_evenement`, `description_evenement`, `image_evenement`) VALUES
('EVENT001', 'Un food truck pour votre mariage, est-ce possible ?', 'La street food règne en maitre sur nos déjeuners, et depuis quelques temps, on retrouve également les désormais célèbres food trucks sur les mariages. Au cocktail, au dîner, ou pour le brunch du lendemain, de nombreux mariés ont choisi de confier les estomacs affamés de leurs invités à ces camions gourmands.\r\n\r\nDes burgers, aux bagels, en passant par les crêpes, etc, louer un food truck pour votre mariage peut avoir de nombreux avantages. En premier lieu le coût, puisque nous proposons des formules abordables. Moins conventionnel et plus décontracté qu’un menu traditionnel, le food truck est convivial et original. N’oubliez pas de prévoir tout de même des chaises et des tables pour que vos invités puissent s’asseoir. Assurez vous que notre pourra prendre en charge tous vos invités, sans imposer trop de temps d’attente.', 'images/evenements/mariage.jpg'),
('EVENT002', 'Vous pensez à un food truck pour l\'organisation d\'un baptême ?', 'Un événement spécial à organiser ? Un bon repas à prévoir ? Mais pas envie de privatiser un restaurant pour autant ? Nous sommes ici pour vous.\r\n\r\nDepuis quelques temps, la street food ne se contente plus de simple repas sur les emplacements habituels mais se lance dans l’offre événementielle. La privatisation des food trucks devient de plus en plus simple et permet d’animer vos repas.\r\n\r\nPlace aux camions au bout de votre jardin le jour d\'une de vos fêtes religieuses qui remplacent petit à petit les traiteurs. Ne vous souciez plus de ce que nous pouvez faire à manger pour vos invités lors de vos événements, apportez votre touche d’originalité et pensez à la location de notre food truck. Un service de qualité, des invités enjoués pour un événement mémorable! Et oui, louer votre propre restaurant chez vous, c’est possible et ce quelque soit la raison !', 'images/evenements/bapteme.jpg'),
('EVENT003', 'Pour un anniversaire original, louez un food truck !', 'Dans quelques mois c’est votre anniversaire et vous souhaitez marquer le coup en organisant une soirée digne de son nom. Bien entendu, pour un anniversaire qui en vaut la chandelle, il vous faut une playlist, un beau cadre mais également un bon repas. \r\n\r\n                                                                                                                C’est généralement au moment où il faut choisir une idée de repas d’anniversaire originale que l’on bloque. Une des solution pour un repas d’anniversaire, est de préparer son propre diner ou alors faire appel à un traiteur (mais cette idée est loin d’être économique..). Inutile de se creuser la tête, Nous avons trouvé la clé du succès pour une soirée réussi! Le tout est de sortir des chantiers battus, c’est pourquoi on vous propose de louer votre propre food truck.', 'images/styles_culinaires/anniversaire.jpg'),
('EVENT004', 'La street est aussi adéquate dans le milieu professionnel !', 'En camion restaurant ou en « food truck », cela fait déjà quelques années que la street food version gastro est de retour ! Non aux sandwichs sur le pouce et oui aux food trucks gastronomiques. \r\n                                                                                                                                     Salade de chef, ingrédients de saisons et plats faits maison : le food truck à tout d’un restaurant et séduit les plus gourmands et les plus intransigeants. Foodtruck classique façon burger à l’américaine, ou camion restaurant gastronomique : la location de food truck pour un evenement professionnel est ultra tendance.\r\n                                                                                                                                     Nous vous proposons de par notre concept, de faire impression décontracter tout en restant professionnel. Vous hésitez encore ? Contactez-nous !', 'images/evenements/seminaire.jpg'),
('EVENT005', 'Eh oui !Les apéritifs ont aussi leur place dans le monde de la street food.', 'L\'été arrive et vous souhaitez commencer à profiter des petit plus de la saison. Seulement un problème s\'impose, les apéritifs vous appréciez les déguster néanmoins pour ce qui est de les préparer c\'est une autre affaire... \r\n                                                                                                                \r\n                                                                                                                Pensez dans ce cas à la street food, car oui, on est aussi de la partie ! Ne tergiversez plus, pensez à nous et arrêtez de perdre votre temps. A l\'Équilibre est là pour vous : apéro\' dinatoires, cocktails, ... On vous propose un max de choix pour que cette période soit ce qu\'elle doit être, c\'est à dire reposante.', 'images/evenements/cocktail.jpg');
